# Generated by Selenium IDE
import json,pytest
from time import sleep
import sys,os
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys


class Testweixin():
    path = os.path.dirname(__file__).strip("testcases").__add__("data/cookie.json")

    def setup_method(self):
        print("参数设置")
        chrome_args = webdriver.ChromeOptions()
        chrome_args.debugger_address = "127.0.0.1:9222"
        self.driver = webdriver.Chrome(options=chrome_args)
        # self.driver = webdriver.Chrome()
        print("设置完成")

    def test_getcookie(self):
        self.driver.get("https://work.weixin.qq.com/wework_admin/frame")
        cookies = self.driver.get_cookies()
        # 以文件流的形式打开文件
        with open(self.path, "w") as f:
        # 存储 cookie 到 cookie.json
            json.dump(cookies, f)
        f.close()

    def test_adddept(self):
        self.driver.get("https://work.weixin.qq.com/wework_admin/frame")
        print("get cookies")

        # 以文件流的形式打开文件
        with open(self.path, "r") as f:
            # 读取 cookies
            cookies = json.load(f)
        # 注入 cookies
        f.close()
        print("got cookies")

        for cookie in cookies:
            # print(cookie["domain"])
            try:
                if cookie["expiry"] != "":
                    del cookie["expiry"]
            except:
                pass
            self.driver.add_cookie(cookie)
        self.driver.get("https://work.weixin.qq.com/wework_admin/frame#index")
        sleep(3)
        self.driver.find_element(By.XPATH, "//*[@id='menu_contacts']").click()

    def test_testweixin(self):
        self.driver.get("https://work.weixin.qq.com/wework_admin/frame")
        print("get cookies")

        # 以文件流的形式打开文件
        with open(self.path, "r") as f:
            # 读取 cookies
            cookies = json.load(f)
        # 注入 cookies
        f.close()
        print("got cookies")

        for cookie in cookies:
            # print(cookie["domain"])
            try:
                if cookie["expiry"] != "":
                    del cookie["expiry"]
            except:
                pass
            self.driver.add_cookie(cookie)
        self.driver.get("https://work.weixin.qq.com/wework_admin/frame#index")
        sleep(3)
        self.driver.find_element(By.XPATH, "//*[@id='menu_contacts']").click()
        sleep(1)
        self.driver.find_element(By.CLASS_NAME, 'member_colLeft_top_addBtn').click()
        self.driver.find_element(By.CLASS_NAME, 'js_create_party').click()
        sleep(1)
        self.driver.find_element(By.NAME, 'name').click()
        self.driver.find_element(By.NAME, 'name').send_keys("部门3")
        self.driver.find_element(By.CLASS_NAME, 'js_toggle_party_list').click()
        # self.driver.find_element(By.XPATH, "//div[@class='js_party_list_container']/div/ul/li/div").click()
        ele=self.driver.find_elements(By.XPATH, "//*[contains(@id,'_anchor')]")
        ele_length = len(ele)

        ele[int(ele_length/2)].click()
        self.driver.find_element(By.XPATH, "//*[@d_ck='submit']").click()
        name_webelement_list = self.driver.find_elements(By.CSS_SELECTOR, ".jstree-open:nth-child(2)")
        print(name_webelement_list)
        name_list = []
        for webelement in name_webelement_list:
            name_list.append(webelement.text)
        print("=======================")
        print(name_list)

    def teardown_method(self):
        self.driver.quit()
if __name__=="__main__":
    pytest.main([r"C:\Users\Dmall-CD-Tech01\PycharmProjects\HogwartsLG5\test_python\src\selenium_demo\selenium_work.py"])