add:
   - [1,2,3]
   - [4,5,9]
   - [0.1,0.2,0.3]
   - [' a',1,5]
sub:
   - [1,2,-1]
   - [6,5,1]
mul:
   - [1,2,2]
   - [4,5,20]
divi:
   - [1,2,0.5]
   - [10,5,2]
add_ids:
        - add1
        - add2
        - add3
        - add4
sub_ids:
        - sub1
        - sub2
mul_ids:
        - mul1
        - mul2
divi_ids:
        - divi1
        - divi2