platformName: Android
deviceName: 127.0.0.1:7555
platformVersion: 6.0.1
appPackage: com.tencent.wework
appActivity: .launch.LaunchSplashActivity
noReset: true
automationName: uiautomator2
unicodeKeyboard: true
resetKeyboard: true
dontStopAppOnReset: true
skipDeviceInitialization: true
browserName: Browser
chromedriverExecutable: F:\\Python3.6.0\\chromedriver224.exe
chromedriverExecutableDir: F:\\Python3.6.0
skipServerInstallation: true
avd: Pixel_3a_API_30_x86
ip: http://localhost
host: :4723/wd/hub