platformName: Android
deviceName: 127.0.0.1:7555
platformVersion: 6.0.1
appPackage: com.xueqiu.android
appActivity: .view.WelcomeActivityAlias
noReset: true
automationName: uiautomator2
unicodeKeyboard: true
resetKeyboard: true
dontStopAppOnReset: true
skipDeviceInitialization: true
settings[waitForIdleTimeout]: 0
browserName: Browser
chromedriverExecutable: F:\\Python3.6.0\\chromedriver224.exe
chromedriverExecutableDir: F:\\Python3.6.0
skipServerInstallation: true
avd: Pixel_3a_API_30_x86
ip: localhost
port: [4723,4725]
udid: [127.0.0.1:62001,127.0.0.1:62025]